name: Auto Update

on:
  # This will trigger on all pushes to all branches.
#  push: {}
  # Alternatively, you can only trigger if commits are pushed to certain branches, e.g.:
  push:
    branches:
      - current
  #     - unstable
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - uses: chinthakagodawita/autoupdate@v1.7.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "auto update"
          PR_READY_STATE: "all"
         # EXCLUDED_LABELS: "do not merge"
          MERGE_MSG: "This branch was auto-updated!"
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "ignore"
          
      - run: echo 'We found merge conflicts when updating this PR. Please fix them as soon as you can.'
        if: ${{ steps.autoupdate.outputs.conflicted }}

      - run: echo 'Good news! No merge conflicts this time around.'
        if: ${{ !steps.autoupdate.outputs.conflicted }}
