name: Vale Lint

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["website/docs/docs", "website/docs/reference","website/docs/guides"]'

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep '\.md\|\.txt\|\.rst' | tr '\n' ' ')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Set up Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Run Vale with Reviewdog
        run: |
          for file in ${{ env.CHANGED_FILES }}; do
            vale --output=JSON "$file" | reviewdog -f=vale -name="vale" -reporter=github-pr-review -level=warning -filter-mode=added -fail-on-error=true -tee
          done
